name: Daily Weather Forecast
on:
  schedule:
    - cron:  "0 13 * * *"   # runs daily at 13:00 UTC (9:00 AM Eastern Time)
jobs:
  post-forecast:
    runs-on: ubuntu-latest
    env:
      PA_WEBHOOK_URL: ${{ secrets.PA_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install requests
      - name: Run Weather Forecast Script
        run: python weather_bot.py
